# Generated by Django 4.0.2 on 2022-03-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0002_rename_bio_profile_about_rename_profile_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.CharField(blank=True, max_length=5, null=True)),
                ('number', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
