# Generated by Django 3.2.12 on 2022-04-07 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studybuddy', '0003_studysession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='users',
        ),
        migrations.AddField(
            model_name='studysession',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
