# Generated by Django 4.0.2 on 2022-04-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0004_remove_course_dep_remove_course_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseName',
        ),
        migrations.AddField(
            model_name='course',
            name='courseAbbv',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='course',
            name='courseNumber',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='course',
            name='courseTitle',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='courseTopic',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
