# Generated by Django 3.2.12 on 2022-04-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0004_auto_20220407_1104'),
        ('studybuddy', '0005_remove_course_coursename_course_courseabbv_and_more'),
    ]

    operations = [
    ]
