# Generated by Django 3.2.12 on 2022-04-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0006_merge_20220412_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='courses',
        ),
    ]
