# Generated by Django 3.2.12 on 2022-04-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0007_remove_profile_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(blank=True, to='studybuddy.Course'),
        ),
    ]
