# Generated by Django 3.2.12 on 2022-04-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0008_profile_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='date',
            field=models.DateField(),
        ),
    ]
