# Generated by Django 3.2.12 on 2022-04-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0009_alter_studysession_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
