# Generated by Django 4.0.2 on 2022-04-26 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studybuddy', '0011_alter_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_session', to=settings.AUTH_USER_MODEL),
        ),
    ]
