# Generated by Django 4.0.3 on 2022-05-01 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0013_messagetwo_created_date_studysession_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='created_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date created'),
        ),
    ]
