# Generated by Django 4.0.2 on 2022-05-02 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0013_messagetwo_created_date_studysession_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
