# Generated by Django 4.0.3 on 2022-05-02 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0014_alter_studysession_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date created'),
        ),
    ]
