# Generated by Django 4.0.2 on 2022-05-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0014_delete_room'),
        ('studybuddy', '0016_studysession_end_date'),
    ]

    operations = [
    ]
