# Generated by Django 4.0.2 on 2022-05-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0017_merge_0014_delete_room_0016_studysession_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(max_length=300),
        ),
    ]
